In [1]:
import os
import pandas as pd

# get the absolute path of the current working directory
cwd = os.getcwd()

# navigate to the Dataset folder
file_path = os.path.join(cwd, '..', 'Dataset', 'modified-test.csv')

# load the CSV file into a Pandas dataframe
data = pd.read_csv(file_path)

In [2]:
import nltk
import string
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer,PorterStemmer
from nltk.tokenize import word_tokenize
from wordcloud import WordCloud, STOPWORDS

stop = set(stopwords.words('english'))

def preprocess_text(text):
    corpus=[]
    #stem=PorterStemmer()
    lem=WordNetLemmatizer()
    for news in text:
        words=[w for w in word_tokenize(news) if (w not in stop)]
        words=[lem.lemmatize(w) for w in words if len(w)>2]
        words = [''.join(c for c in s if c not in string.punctuation) for s in words if s]
        words = [word.lower() for word in words]
        words = [word for word in words if word.isalpha()]
        corpus.append(words) 

    return corpus     
      
data['processed_comment_text']= preprocess_text(data['comment_text'])

In [3]:
data.head()

,comment_text,toxicity,severe_toxicity,obscene,sexual_explicit,identity_attack,insult,threat,other,gender,religion,race,disability,Target,processed_comment_text
0,At about this point: It participated with the ...,0.000000,0,0,0,0,0,0,1,1,0,0,0,0,"[point, participated, federation, south, afric..."
1,"In my lifetime, in my society, I've seen the p...",0.000000,0,0,0,0,0,0,1,0,0,0,0,0,"[lifetime, society, ve, seen, power, shift, ma..."
2,Perhaps lower reproduction rates are a choice....,0.000000,0,0,0,0,0,0,1,0,0,0,0,0,"[perhaps, lower, reproduction, rate, choice, n..."
3,BS !,0.000000,0,0,0,0,0,0,1,0,0,0,0,0,[]
4,Corrupt hypocrites throughout he government. O...,0.716216,0,0,0,0,1,0,0,0,0,0,0,1,"[corrupt, hypocrite, throughout, government, m..."

In [4]:
#Viewing the processed text.
data['processed_comment_text']

0        [point, participated, federation, south, afric...
1        [lifetime, society, ve, seen, power, shift, ma...
2        [perhaps, lower, reproduction, rate, choice, n...
3                                                       []
4        [corrupt, hypocrite, throughout, government, m...
                               ...
21278    [there, opinion, lie, shannyn, probably, know,...
21279    [ll, limb, ll, see, go, view, twelve, remained...
21280    [there, cut, medicaid, proposal, slow, growth,...
21281    [domestic, violence, real, issue, need, attent...
21282    [this, argument, skewed, corporate, owned, med...
Name: processed_comment_text, Length: 21283, dtype: object

In [5]:
#Finding and printing the maximum length of the sentence in the processed text
lgt = []
for i in data['processed_comment_text']:
  lgt.append(len(i))
print('Maximum length of the sentence in processed text (in list) :',max(lgt))

Maximum length of the sentence in processed text (in list) : 114

In [6]:
comment_processed = []
for i in range(len(data['processed_comment_text'])):
   comment_processed.append(' '.join(wrd for wrd in data.iloc[:,14][i]))
data['comment_text_processed'] = comment_processed
data.head()

,comment_text,toxicity,severe_toxicity,obscene,sexual_explicit,identity_attack,insult,threat,other,gender,religion,race,disability,Target,processed_comment_text,comment_text_processed
0,At about this point: It participated with the ...,0.000000,0,0,0,0,0,0,1,1,0,0,0,0,"[point, participated, federation, south, afric...",point participated federation south african wo...
1,"In my lifetime, in my society, I've seen the p...",0.000000,0,0,0,0,0,0,1,0,0,0,0,0,"[lifetime, society, ve, seen, power, shift, ma...",lifetime society ve seen power shift male fema...
2,Perhaps lower reproduction rates are a choice....,0.000000,0,0,0,0,0,0,1,0,0,0,0,0,"[perhaps, lower, reproduction, rate, choice, n...",perhaps lower reproduction rate choice nt know...
3,BS !,0.000000,0,0,0,0,0,0,1,0,0,0,0,0,[],
4,Corrupt hypocrites throughout he government. O...,0.716216,0,0,0,0,1,0,0,0,0,0,0,1,"[corrupt, hypocrite, throughout, government, m...",corrupt hypocrite throughout government money ...

In [7]:
data.isnull().sum()

comment_text              0
toxicity                  0
severe_toxicity           0
obscene                   0
sexual_explicit           0
identity_attack           0
insult                    0
threat                    0
other                     0
gender                    0
religion                  0
race                      0
disability                0
Target                    0
processed_comment_text    0
comment_text_processed    0
dtype: int64

In [8]:
data = data.dropna()
data.isnull().sum()

comment_text              0
toxicity                  0
severe_toxicity           0
obscene                   0
sexual_explicit           0
identity_attack           0
insult                    0
threat                    0
other                     0
gender                    0
religion                  0
race                      0
disability                0
Target                    0
processed_comment_text    0
comment_text_processed    0
dtype: int64

In [9]:
data.to_csv('final-test.csv', index=False)

In [10]:
'''
from sklearn.model_selection import train_test_split

# Split the data into training and test sets, with 70% for training and 30% for testing
train_data, test_data = train_test_split(data, test_size=0.3, random_state=42)

train_data.to_csv('train.csv', index=False)
test_data.to_csv('test.csv', index=False)
'''

"\nfrom sklearn.model_selection import train_test_split\n\n# Split the data into training and test sets, with 70% for training and 30% for testing\ntrain_data, test_data = train_test_split(data, test_size=0.3, random_state=42)\n\ntrain_data.to_csv('train.csv', index=False)\ntest_data.to_csv('test.csv', index=False)\n"